## Exercises - Basic SQL Queries

Here are some of the exercises for which you can write SQL queries to self evaluate using all the concepts we have learnt to write SQL Queries.
* All the exercises are based on retail tables.
* We have already setup the tables and also populated the data.
* We will use all the 6 tables in retail database as part of these exercises.

In [1]:
%load_ext sql

In [2]:
%env DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

env: DATABASE_URL=postgresql://itversity_retail_user:itversity@localhost:5432/itversity_retail_db

In [ ]:
%sql SELECT count(*) FROM departments

In [ ]:
%sql SELECT count(*) FROM categories

In [ ]:
%sql SELECT count(*) FROM products

In [ ]:
%sql SELECT count(*) FROM customers

In [ ]:
%sql SELECT count(*) FROM orders

In [ ]:
%sql SELECT count(*) FROM order_items

### Exercise 1 - Customer order count

Get order count per customer for the month of 2014 January.

* Tables - `orders` and `customers`
* Data should be sorted in descending order by count and ascending order by customer id.
* Output should contain `customer_id`, `customer_fname`, `customer_lname` and `customer_order_count`.

### Exercise 2 - Dormant Customers

Get the customer details who have not placed any order for the month of 2014 January.
* Tables - `orders` and `customers`
* Output Columns - **All columns from customers as is**
* Data should be sorted in ascending order by `customer_id`
* Output should contain all the fields from `customers`
* Make sure to run below provided validation queries and validate the output.

```sql
SELECT count(DISTINCT order_customer_id)
FROM orders
WHERE to_char(order_date, 'yyyy-MM') = '2014-01';

SELECT count(*)
FROM customers;

-- Get the difference
-- Get the count using solution query, both the difference and this count should match
```
* Hint: You can use `NOT IN` or `NOT EXISTS` or `OUTER JOIN` to solve this problem.

### Exercise 3 - Revenue Per Customer

Get the revenue generated by each customer for the month of 2014 January
* Tables - `orders`, `order_items` and `customers`
* Data should be sorted in descending order by revenue and then ascending order by `customer_id`
* Output should contain `customer_id`, `customer_fname`, `customer_lname`, `customer_revenue`.
* If there are no orders placed by customer, then the corresponding revenue for a given customer should be 0.
* Consider only `COMPLETE` and `CLOSED` orders

### Exercise 4 - Revenue Per Category

Get the revenue generated for each category for the month of 2014 January
* Tables - `orders`, `order_items`, `products` and `categories`
* Data should be sorted in ascending order by `category_id`.
* Output should contain all the fields from `categories` along with the revenue as `category_revenue`.
* Consider only `COMPLETE` and `CLOSED` orders

### Exercise 5 - Product Count Per Department

Get the count of products for each department.
* Tables - `departments`, `categories`, `products`
* Data should be sorted in ascending order by `department_id`
* Output should contain all the fields from `departments` and the product count as `product_count`