## Managing Spark Metastore Tables

Let us create our first Spark Metastore table. We will also have a look into how to list the tables.

* We will get into details related to DDL Commands at a later point in time. 
* For now we will just create our first table. We will get into the details about creating tables as part of subsequent sections.

In [ ]:
%sql
SELECT current_database()

In [ ]:
%sql
SHOW databases

In [ ]:
%sql
DROP DATABASE IF EXISTS itversity_retail CASCADE

In [ ]:
%sql
SHOW databases

In [ ]:
%sql
CREATE DATABASE IF NOT EXISTS itversity_retail

In [ ]:
%sql
USE itversity_retail

In [ ]:
%sql
SELECT current_database()

In [ ]:
%sql
CREATE TABLE orders (
    order_id INT,
    order_date STRING,
    order_customer_id INT,
    order_status STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY ','

* We can list the tables using `SHOW tables;`

In [ ]:
%sql
SHOW tables

In [ ]:
%sql
SELECT * FROM orders

In [ ]:
%sql
SELECT count(*) FROM orders;

In [ ]:
%sql
DESCRIBE FORMATTED orders

In [ ]:
%fs ls /public/retail_db/orders

In [ ]:
%fs cp /public/retail_db/orders/part-00000 /user/hive/warehouse/itversity_retail.db/orders/part-00000

In [ ]:
%sql
SELECT * FROM orders

In [ ]:
%sql
SELECT count(*) FROM orders

* We can also drop the table using `DROP TABLE` command. We will get into more details at a later point in time.
* We can also truncate the managed tables using `TRUNCATE TABLE` command.

In [ ]:
%sql
DROP TABLE itversity_retail.orders

In [ ]:
%fs ls /user/hive/warehouse/itversity_retail.db

In [ ]:
%sql
DROP DATABASE IF EXISTS itversity_retail CASCADE