## Exercise - Getting Started with Spark SQL

Let's do a simple exercise to conclude this section.

* Drop **itversity_retail** Database if it already exists. Use `CASCADE` so that the database is dropped even if it is not empty.
* Create Database by name `itversity_retail` and then switch to the database.
* Create Table orders. You can use below script to create the table.

```
CREATE TABLE orders (
  order_id INT,
  order_date STRING,
  order_customer_id INT,
  order_status STRING
) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',';
```

* List the tables
* Describe the table and review the whole metadata.
* Finally drop **itversity_retail** database to keep it clean.